import Home3Team from "@/components/Team/Home3Team";
import About3 from "@/components/about/About3";
import Banner3 from "@/components/bannner/Banner3";
import Banner4 from "@/components/bannner/Banner4";
import About4 from "@/components/about/About4";

import Home3Blog from "@/components/blog/Home3Blog";
import Preloader from "@/components/common/Preloader";
import Home3Contact from "@/components/contact/Home3Contact";
import Footer3 from "@/components/footer/Footer3";
import Header from "@/components/header/Header";
import Partner3 from "@/components/partner/Partner3";
import PricingPlan3 from "@/components/pricingplan/PricingPlan3";
import Pricing from "@/components/pricingplan/Pricing4";
import Solution3 from "@/components/solutions/Solution3";
import SuccessStory3 from "@/components/successStorys/SuccessStory3";
import Testimonial3 from "@/components/testimonial/Testimonial3";
import useBodyClass from "@/hooks/useBodyClass";
import Head from "next/head";

export default function Home() {
  useBodyClass("home-dark2");

  const CalculatorSection = () =>
    <div className="home3-solution-section sec-mar">
      <div className="container">
        <div className="row justify-content-center g-4">
          <div
            className="col-lg-6 col-md-6 col-sm-10 wow animate fadeInUp"
            data-wow-delay="300ms"
            data-wow-duration="1500ms"
          >
            <div className="section-title-4">
            <span>Higring Insights</span>
            <h2>Calculate the cost too hire an employee in a new country</h2>
            </div>
          </div>
          <div
            className="col-lg-6 col-md-6 col-sm-10 wow animate fadeInUp"
            data-wow-delay="400ms"
            data-wow-duration="1500ms"
          >
            <div className="faq-page">
              <div className="contact-form-wrap">
               
                <div className="contact-form">
                  <form>
                    <div className="row">
                      <div className="col-md-12 mb-20">
                        <div className="form-inner">
                          <select className="form-select" id="country" aria-label="Select a country you want hire">
                            <option value="1">Select a country you want hire</option>
                            <option value="2">India</option>
                            <option value="3">Bahrain</option>
                            <option value="4">UAE</option>
                            <option value="5">UK</option>
                            <option value="6">USA</option>
                          </select>
                        </div>
                      </div>
                      <div className="col-lg-6 mb-20">
                        <div className="form-inner">
                          <select className="form-select" id="currency" aria-label="Currency">
                            <option value="1">Currency</option>
                            <option value="2">INR</option>
                            <option value="3">BHD</option>
                            <option value="3">USD</option>
                          </select>
                        </div>
                      </div>
                      <div className="col-lg-6 mb-20">
                        <div className="form-inner">
                          <input type="text" placeholder="gross Annual salary"/>
                        </div>
                      </div>
                      <div className="col-lg-12 mb-20 ">
                        <div className="d-flex flex-row">
                        <p>Eligible to work in India?</p>
                          <div className="form-check">
                            <input className="radio-btn" type="radio" name="inlineCheckbox" />
                            <label className="form-check-label" for="inlineCheckbox">Yes</label>
                          </div>
                          <div class="form-check">
                            <input className="radio-btn" type="radio" name="inlineCheckbox"  />
                            <label className="form-check-label" for="inlineCheckbox">No</label>
                          </div>
                      </div>
                      </div>
                                          
                      <div className="col-lg-12 text-center">
                        <div className="form-inner">
                          <button className="primary-btn3" type="submit">
                            Calculate
                          </button>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>;


  return (
    <>
      <Head>
        <title>
          Connect by Vinpro
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/sm-logo.svg" />
      </Head>

      <Header />
      <Banner3 />
      <CalculatorSection />

      <About4 />
      <Pricing />
      <Home3Contact />

      {/* <Partner3 /> 
      <Solution3 />
      <About3 />
      <SuccessStory3 />
      <Testimonial3 />
      <PricingPlan3 />
      <Home3Contact />
      <Home3Team />
      <Home3Blog />*/}
      <Footer3 />
    </>
  );
}
